services:
  pio-compiler:
    build: .
    image: pio-compiler:latest
    container_name: pio-compiler
    restart: unless-stopped
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
