export const szpiEsp32s3DriverContracts = [
  {
    id: 'display.lvgl-ui',
    skillId: 'lvgl',
    layer: 'L3-driver-contract',
    label: 'LVGL display and touch UI',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lvgl_start',
    ],
    allowedApis: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lvgl_start',
      'bsp_display_brightness_set',
      'lvgl_port_lock',
      'lvgl_port_unlock',
      'lv_*',
    ],
    forbiddenApis: [
      'esp_lvgl_util.h',
      'lv_font_montserrat_24',
      'lv_font_montserrat_28',
    ],
    requiredComponents: [
      'lvgl/lvgl',
      'espressif/esp_lvgl_port',
      'espressif/esp_lcd_touch_ft5x06',
    ],
    acceptanceChecks: [
      'LCD backlight turns on',
      'UI object is created after bsp_lvgl_start',
      'task-owned LVGL updates are wrapped by lvgl_port_lock/unlock',
    ],
    commonFailures: [
      'pca9557_init missing before display init',
      'LVGL called from another task without lvgl_port_lock',
      'AI selected an LVGL font that sdkconfig does not enable',
    ],
  },
  {
    id: 'display.raw-lcd',
    skillId: 'camera',
    layer: 'L3-driver-contract',
    label: 'Raw ST7789 LCD drawing',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lcd_init',
    ],
    allowedApis: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lcd_init',
      'bsp_display_brightness_set',
      'lcd_draw_bitmap',
    ],
    forbiddenApis: [
      'manual LCD GPIO remap',
      'direct LCD CS GPIO control',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'LCD accepts RGB565 bitmap draws',
      'display buffer dimensions do not exceed 320x240',
    ],
    commonFailures: [
      'LCD CS is controlled by PCA9557, not a direct GPIO',
      'wrong RGB565 byte order',
    ],
  },
  {
    id: 'camera.capture',
    skillId: 'camera',
    layer: 'L3-driver-contract',
    label: 'GC0308 DVP camera capture',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lcd_init',
      'delay_500ms',
      'bsp_camera_init',
    ],
    allowedApis: [
      'bsp_camera_init',
      'esp_camera_fb_get',
      'esp_camera_fb_return',
      'lcd_draw_bitmap',
    ],
    forbiddenApis: [
      'dvp_pwdn',
      'gpio_set_level(GPIO46, 1)',
      'manual camera pin map',
    ],
    requiredComponents: [
      'espressif/esp32-camera',
    ],
    acceptanceChecks: [
      'camera init happens after LCD stabilize delay',
      'every esp_camera_fb_get frame is returned',
      'frame buffers live in PSRAM-compatible configuration',
    ],
    commonFailures: [
      'missing 500ms delay after LCD init',
      'manual DVP PWDN handling fights BSP',
      'GPIO46 is driven high during boot',
    ],
  },
  {
    id: 'input.boot-button',
    skillId: 'gpio',
    layer: 'L3-driver-contract',
    label: 'BOOT button GPIO interrupt',
    requiredInit: [
      'gpio_config(GPIO0 input pullup)',
      'gpio_install_isr_service',
      'gpio_isr_handler_add',
    ],
    allowedApis: [
      'gpio_config',
      'gpio_get_level',
      'gpio_install_isr_service',
      'gpio_isr_handler_add',
      'xQueueSendFromISR',
    ],
    forbiddenApis: [
      'configure GPIO0 as output',
      'long work inside ISR',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'GPIO0 is active low with pull-up enabled',
      'ISR only posts to a queue or sets a lightweight flag',
    ],
    commonFailures: [
      'BOOT button not pulled up',
      'blocking work done inside interrupt handler',
    ],
  },
  {
    id: 'network.wifi-sta',
    skillId: 'wifi',
    layer: 'L3-driver-contract',
    label: 'WiFi station networking',
    requiredInit: [
      'nvs_flash_init_with_erase_fallback',
      'esp_netif_init',
      'esp_event_loop_create_default',
      'esp_wifi_init',
      'esp_wifi_start',
    ],
    allowedApis: [
      'nvs_flash_init',
      'nvs_flash_erase',
      'esp_netif_init',
      'esp_event_loop_create_default',
      'esp_wifi_init',
      'esp_wifi_set_mode',
      'esp_wifi_set_config',
      'esp_wifi_start',
      'esp_wifi_connect',
    ],
    forbiddenApis: [
      'start WiFi before NVS',
      'factory partition smaller than 7M for WiFi apps',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'NVS initializes before WiFi',
      'network failures emit ESP_LOG messages',
      'WiFi app uses generated large partition table',
    ],
    commonFailures: [
      'NVS not initialized before WiFi',
      'partition too small for network-enabled firmware',
    ],
  },
  {
    id: 'audio.codec-playback',
    skillId: 'audio',
    layer: 'L3-driver-contract',
    label: 'ES8311 speaker playback',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lvgl_start',
      'bsp_spiffs_mount',
      'bsp_codec_init',
      'audio_player_new',
    ],
    allowedApis: [
      'bsp_audio_init',
      'bsp_codec_init',
      'bsp_codec_set_fs',
      'bsp_spiffs_mount',
      'audio_player_*',
      'pa_en',
    ],
    forbiddenApis: [
      'pa_en(1) outside audio PLAYING callback',
      'hard-coded ES8311 address other than 0x18',
      'change I2S pins manually',
    ],
    requiredComponents: [
      'chmorgan/esp-audio-player',
      'espressif/esp_lcd_touch_ft5x06',
    ],
    acceptanceChecks: [
      'audio codec initializes without I2C error',
      'speaker PA is enabled only while playback is active',
      'playback failures are logged',
    ],
    commonFailures: [
      'speaker silent because pa_en(1) is missing',
      'PA enabled too early and causes pop/noise',
      'codec sample rate conflicts with speech pipeline',
    ],
  },
  {
    id: 'audio.mic-feed',
    skillId: 'audio',
    layer: 'L3-driver-contract',
    label: 'ES7210 microphone feed',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_audio_init',
      'bsp_codec_init',
    ],
    allowedApis: [
      'bsp_audio_init',
      'bsp_codec_init',
      'bsp_codec_set_fs',
      'esp_get_feed_channel',
      'esp_get_feed_data',
    ],
    forbiddenApis: [
      'hard-coded ES7210 address 0x40',
      'change I2S pins manually',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'microphone feed returns nonzero samples',
      'feed buffer uses the channel count reported by esp_get_feed_channel',
    ],
    commonFailures: [
      'ES7210 address is 0x41 because AD0 is wired high',
      'buffer length does not match feed channel count',
    ],
  },
  {
    id: 'storage.sdcard',
    skillId: 'sdcard',
    layer: 'L3-driver-contract',
    label: 'SDMMC 1-bit microSD storage',
    requiredInit: [
      'bsp_sdcard_mount',
    ],
    allowedApis: [
      'bsp_sdcard_mount',
      'esp_vfs_fat_sdmmc_mount',
      'sdmmc_*',
      'fopen',
      'fread',
      'fwrite',
      'fclose',
    ],
    forbiddenApis: [
      'SDMMC 4-bit mode',
      'manual SDMMC pin remap',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'SD card mounts at /sdcard',
      'slot width remains 1-bit',
      'file IO errors are logged',
    ],
    commonFailures: [
      'slot.width not set to 1',
      'missing internal pullups',
      'code assumes /mnt/sdcard instead of /sdcard',
    ],
  },
  {
    id: 'sensor.imu-qmi8658',
    skillId: 'imu',
    layer: 'L3-driver-contract',
    label: 'QMI8658 IMU attitude sensor',
    requiredInit: [
      'bsp_i2c_init',
      'qmi8658_init',
    ],
    allowedApis: [
      'bsp_i2c_init',
      'qmi8658_init',
      'qmi8658_fetch_angleFromAcc',
      'qmi8658_fetch_gyro',
      'qmi8658_fetch_acc',
    ],
    forbiddenApis: [
      'I2C address 0x6B',
      'second I2C bus for onboard IMU',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'IMU initializes at I2C address 0x6A',
      'angle or acceleration readings are logged',
    ],
    commonFailures: [
      'AI uses 0x6B instead of 0x6A',
      'I2C bus is not initialized first',
    ],
  },
  {
    id: 'bluetooth.ble-hid',
    skillId: 'ble',
    layer: 'L3-driver-contract',
    label: 'BLE HID device',
    requiredInit: [
      'nvs_flash_init_with_erase_fallback',
      'esp_bt_controller_init',
      'esp_bluedroid_init',
      'app_hid_ctrl',
    ],
    allowedApis: [
      'nvs_flash_init',
      'esp_bt_*',
      'esp_ble_*',
      'esp_hidd_*',
      'app_hid_ctrl',
    ],
    forbiddenApis: [
      'Bluetooth Classic',
      'BLE 5 only features',
      'BT stack before NVS',
    ],
    requiredComponents: [],
    acceptanceChecks: [
      'BLE initializes after NVS',
      'device advertises as HID',
      'connection state is logged',
    ],
    commonFailures: [
      'NVS missing before BT stack',
      'ESP32-S3 does not support Classic Bluetooth',
      'BLE 5 configs conflict with BLE 4.2 HID example',
    ],
  },
  {
    id: 'speech.recognition',
    skillId: 'speech',
    layer: 'L3-driver-contract',
    label: 'ESP-SR speech recognition',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lvgl_start',
      'bsp_spiffs_mount',
      'bsp_codec_init',
      'app_sr_init',
    ],
    allowedApis: [
      'app_sr_init',
      'esp_afe_*',
      'esp_mn_*',
      'esp_srmodel_*',
      'esp_get_feed_data',
      'bsp_codec_set_fs',
    ],
    forbiddenApis: [
      'feed buffer from internal RAM for large SR buffers',
      'change I2S sample rate while speech pipeline is active',
    ],
    requiredComponents: [
      'espressif/esp-sr',
      'chmorgan/esp-audio-player',
    ],
    acceptanceChecks: [
      'speech models load from SPIFFS',
      'AFE task starts',
      'recognized command or wake state is logged',
    ],
    commonFailures: [
      'speech buffers not allocated from PSRAM',
      'model files missing from SPIFFS',
      'I2S clock changed by audio playback',
    ],
  },
  {
    id: 'vision.camera-detect',
    skillId: 'vision',
    layer: 'L3-driver-contract',
    label: 'Camera-based vision detection',
    requiredInit: [
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lcd_init',
      'delay_500ms',
      'bsp_camera_init',
      'load model buffers from PSRAM',
    ],
    allowedApis: [
      'bsp_camera_init',
      'esp_camera_fb_get',
      'esp_camera_fb_return',
      'lcd_draw_bitmap',
      'coco_detect_*',
      'who_*',
    ],
    forbiddenApis: [
      'model buffers in internal RAM',
      'manual camera pin map',
      'generate CMakeLists for model requirements',
    ],
    requiredComponents: [
      'espressif/esp32-camera',
    ],
    acceptanceChecks: [
      'camera frames are captured and returned',
      'detection task logs inference status',
      'large buffers are PSRAM-backed',
    ],
    commonFailures: [
      'C++ vision source planned without .cpp entry',
      'model memory exceeds internal RAM',
      'camera init order does not follow LCD delay',
    ],
  },
  {
    id: 'device.handheld-full-stack',
    skillId: 'handheld',
    layer: 'L3-driver-contract',
    label: 'Combined handheld device stack',
    requiredInit: [
      'nvs_flash_init_with_erase_fallback',
      'bsp_i2c_init',
      'pca9557_init',
      'bsp_lvgl_start',
      'bsp_spiffs_mount',
      'bsp_codec_init',
      'delay_500ms',
      'bsp_camera_init when camera is used',
    ],
    allowedApis: [
      'bsp_lvgl_start',
      'bsp_camera_init',
      'bsp_codec_init',
      'bsp_spiffs_mount',
      'esp_wifi_*',
      'esp_ble_*',
      'audio_player_*',
      'lv_*',
    ],
    forbiddenApis: [
      'factory partition smaller than 8M',
      'unbounded task stack growth',
      'manual pin remap for onboard peripherals',
    ],
    requiredComponents: [
      'lvgl/lvgl',
      'espressif/esp_lvgl_port',
      'espressif/esp32-camera',
      'chmorgan/esp-audio-player',
    ],
    acceptanceChecks: [
      'main UI starts',
      'selected device features initialize in deterministic order',
      'memory-sensitive tasks log failures',
    ],
    commonFailures: [
      'combined features exceed partition or memory budget',
      'WiFi/BLE/audio coexistence needs conservative SPIRAM settings',
      'camera and LCD init order is wrong',
    ],
  },
]

export function getDriverContractsForSkillIds(skillIds = []) {
  const selected = new Set(skillIds || [])
  return szpiEsp32s3DriverContracts.filter(contract => selected.has(contract.skillId))
}

export function getDriverContractById(id) {
  return szpiEsp32s3DriverContracts.find(contract => contract.id === id) || null
}
