import { getBoard } from './boards/index'

const SKILL_CONFIG_REQUIREMENTS = {
  audio: ['lvgl'],
  wifi: ['lvgl'],
  ble: ['lvgl'],
  speech: ['audio', 'lvgl'],
  vision: ['camera'],
}

export function expandSelectedSkillIds(board, selectedSkillIds = []) {
  const valid = new Set((board?.skills || []).map(skill => skill.id))
  const expanded = new Set((selectedSkillIds || []).filter(id => valid.has(id)))

  let changed = true
  while (changed) {
    changed = false
    for (const [skillId, requiredSkillIds] of Object.entries(SKILL_CONFIG_REQUIREMENTS)) {
      if (!expanded.has(skillId)) continue
      for (const requiredSkillId of requiredSkillIds) {
        if (valid.has(requiredSkillId) && !expanded.has(requiredSkillId)) {
          expanded.add(requiredSkillId)
          changed = true
        }
      }
    }
  }

  return [...expanded]
}

export function buildSystemPrompt(boardId, selectedSkillIds = []) {
  const board = getBoard(boardId)
  if (!board) throw new Error(`Unknown board: ${boardId}`)
  const effectiveSkillIds = expandSelectedSkillIds(board, selectedSkillIds)

  const skillPrompts = board.skills
    .filter(s => effectiveSkillIds.includes(s.id))
    .map(s => s.systemPrompt)
    .filter(Boolean)
    .join('\n\n')

  return skillPrompts ? `${board.basePrompt}\n\n${skillPrompts}` : board.basePrompt
}

export function buildProjectFiles(boardId, projectName, selectedSkillIds = []) {
  const board = getBoard(boardId)
  if (!board) throw new Error(`Unknown board: ${boardId}`)
  const effectiveSkillIds = expandSelectedSkillIds(board, selectedSkillIds)

  const skills = board.skills.filter(s => effectiveSkillIds.includes(s.id))
  const configs = skills.map(s => s.projectConfig).filter(Boolean)

  const needsCpp = configs.some(c => c.mainExt === 'cpp')
  const mainFile = needsCpp ? 'main.cpp' : 'main.c'
  const srcs = [mainFile, ...new Set(configs.flatMap(c => c.systemSrcs || []))]

  const sdkBase = [
    '# Generated by VibeBoard',
    `CONFIG_IDF_TARGET="${board.idfTarget || 'esp32s3'}"`,
  ]
  const flashSize = board.flashSize || '16MB'
  if (flashSize.endsWith('MB')) {
    sdkBase.push(`CONFIG_ESPTOOLPY_FLASHSIZE_${flashSize}=y`)
  }
  const sdkExtra = [...new Set(configs.flatMap(c => c.sdkconfig || []))]
  const sdkconfig = [...sdkBase, ...sdkExtra].join('\n')

  const components = [...new Set(configs.flatMap(c => c.idfComponents || []))]
  const cmakeRequires = ['esp32_s3_szp', ...components.map(componentToRequireName)]
  const idfComponentYml = components.length > 0
    ? `# IDF Component Manager Manifest File\ndependencies:\n` +
      components.map(c => `  ${c}`).join('\n') +
      `\n  idf:\n    version: ">=5.0"`
    : null

  const allPartitions = configs.map(c => c.partitions).filter(Boolean)
  const partitionsCsv = allPartitions.length > 0
    ? mergePartitions(allPartitions).join('\n')
    : null

  const needsSpiffs = configs.some(c => c.spiffs)
  const compileOpts = [...new Set(configs.flatMap(c => c.compileOptions || []))]

  const srcList = srcs.map(s => `"${s}"`).join('\n                    ')
  let mainCmake = `idf_component_register(SRCS ${srcList}\n                    INCLUDE_DIRS ".")`
  if (cmakeRequires.length > 0) {
    mainCmake = `idf_component_register(SRCS ${srcList}\n                    INCLUDE_DIRS "."\n                    REQUIRES ${cmakeRequires.join(' ')})`
  }
  if (needsSpiffs) {
    mainCmake += `\n\nspiffs_create_partition_image(storage ../spiffs FLASH_IN_PROJECT)`
  }
  if (compileOpts.length > 0) {
    mainCmake += `\ntarget_compile_options(\${COMPONENT_LIB} PRIVATE ${compileOpts.join(' ')})`
  }

  const files = {
    'CMakeLists.txt': `cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(${projectName})`,
    'main/CMakeLists.txt': mainCmake,
    'sdkconfig.defaults': sdkconfig,
    '__mainFile': mainFile,
    '__idfTarget': board.idfTarget || 'esp32s3',
    '__selectedSkills': effectiveSkillIds,
  }
  if (idfComponentYml) files['main/idf_component.yml'] = idfComponentYml
  if (partitionsCsv) files['partitions.csv'] = partitionsCsv

  return files
}

function componentToRequireName(component) {
  return String(component)
    .split(':')[0]
    .trim()
    .split('/')
    .pop()
}

function mergePartitions(partitionSets) {
  const header = '# Name,   Type, SubType, Offset,  Size, Flags'
  const byName = new Map()

  for (const lines of partitionSets) {
    for (const line of lines) {
      const trimmed = String(line).trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const parts = trimmed.split(',').map(part => part.trim())
      const name = parts[0]
      if (!name) continue
      const current = byName.get(name)
      if (!current || partitionSizeBytes(parts[4]) > partitionSizeBytes(current.parts[4])) {
        byName.set(name, { original: trimmed, parts })
      }
    }
  }

  const preferredOrder = ['nvs', 'phy_init', 'factory', 'storage', 'model']
  const lines = [header]
  for (const name of preferredOrder) {
    if (byName.has(name)) lines.push(byName.get(name).original)
  }
  for (const [name, entry] of byName.entries()) {
    if (!preferredOrder.includes(name)) lines.push(entry.original)
  }
  return lines
}

function partitionSizeBytes(size) {
  const value = String(size || '').trim().toLowerCase()
  const match = value.match(/^(\d+)(k|m|kb|mb)?$/)
  if (!match) return 0
  const n = parseInt(match[1], 10)
  const unit = match[2] || ''
  if (unit.startsWith('m')) return n * 1024 * 1024
  if (unit.startsWith('k')) return n * 1024
  return n
}

export function patchSkill(boardId, skillId, type, content) {
  const board = getBoard(boardId)
  if (!board) return null

  const skill = board.skills.find(s => s.id === skillId)
  if (!skill) return null

  const section = type === 'pitfall' ? '### Pitfalls' : '### Usage'
  const entry = `- ${content}`
  if (skill.systemPrompt && skill.systemPrompt.includes(section)) {
    skill.systemPrompt = skill.systemPrompt.replace(section, `${section}\n${entry}`)
  } else {
    skill.systemPrompt = (skill.systemPrompt || '') + `\n\n${section}\n${entry}`
  }
  return skill
}
