/**
 * Board-aware context API.
 *
 * All functions take boardId as first parameter — the system loads
 * the correct board definition and skills automatically.
 *
 * Usage:
 *   buildSystemPrompt('szpi_esp32s3', ['lvgl', 'wifi'])
 *   buildProjectFiles('szpi_esp32s3', 'my_app', ['lvgl'])
 *   patchSkill('szpi_esp32s3', 'lvgl', 'pitfall', '...')
 */

import { getBoard } from './boards/index'

// ── System Prompt Assembly ────────────────────────────────────

/** Build AI system prompt: base context + selected skills' prompts */
export function buildSystemPrompt(boardId, selectedSkillIds = []) {
  const board = getBoard(boardId)
  if (!board) throw new Error(`Unknown board: ${boardId}`)

  const skillPrompts = board.skills
    .filter(s => selectedSkillIds.includes(s.id))
    .map(s => s.systemPrompt)
    .filter(Boolean)
    .join('\n\n')

  return skillPrompts ? `${board.basePrompt}\n\n${skillPrompts}` : board.basePrompt
}

// ── Project File Generation ───────────────────────────────────

/**
 * Build complete project files for a given board + skills.
 * Returns a map of { 'filename': 'content' } plus metadata keys (__XXX).
 *
 * The output structure depends on the board's framework:
 *   - 'esp-idf' → CMakeLists.txt, sdkconfig.defaults, main/*.c
 *   - 'arduino' → sketch.ino, __libraries[], __boardFqbn
 *   - 'stm32cube' → Makefile, Src/main.c, Inc/, Drivers/
 */
export function buildProjectFiles(boardId, projectName, selectedSkillIds = []) {
  const board = getBoard(boardId)
  if (!board) throw new Error(`Unknown board: ${boardId}`)

  if (board.framework === 'arduino') {
    return buildArduinoProjectFiles(board, projectName, selectedSkillIds)
  }
  if (board.framework === 'stm32cube') {
    return buildStm32CubeProjectFiles(board, projectName, selectedSkillIds)
  }
  // Default: ESP-IDF
  return buildIdfProjectFiles(board, projectName, selectedSkillIds)
}

// ── ESP-IDF Framework ─────────────────────────────────────────

function buildIdfProjectFiles(board, projectName, selectedSkillIds) {
  const skills = board.skills.filter(s => selectedSkillIds.includes(s.id))
  const configs = skills.map(s => s.projectConfig).filter(Boolean)

  const needsCpp = configs.some(c => c.mainExt === 'cpp')
  const mainFile = needsCpp ? 'main.cpp' : 'main.c'
  const srcs = [mainFile, ...new Set(configs.flatMap(c => c.srcs || []))]

  const sdkBase = [
    '# Generated by esp32-vibe-coder',
    `CONFIG_IDF_TARGET="${board.idfTarget || 'esp32s3'}"`,
  ]
  // Flash size from board definition, default 16MB
  const flashSize = board.flashSize || '16MB'
  if (flashSize.endsWith('MB')) {
    sdkBase.push(`CONFIG_ESPTOOLPY_FLASHSIZE_${flashSize}=y`)
  }
  const sdkExtra = [...new Set(configs.flatMap(c => c.sdkconfig || []))]
  const sdkconfig = [...sdkBase, ...sdkExtra].join('\n')

  const components = [...new Set(configs.flatMap(c => c.idfComponents || []))]
  const idfComponentYml = components.length > 0
    ? `# IDF Component Manager Manifest File\ndependencies:\n` +
      components.map(c => `  ${c}`).join('\n') +
      `\n  idf:\n    version: ">=5.0"`
    : null

  const allPartitions = configs.map(c => c.partitions).filter(Boolean)
  function factorySize(lines) {
    const line = lines.find(l => l.includes('factory'))
    if (!line) return 0
    const m = line.match(/(\d+)M/)
    return m ? parseInt(m[1]) : 0
  }
  const partitionsCsv = allPartitions.length > 0
    ? allPartitions.reduce((a, b) => factorySize(a) >= factorySize(b) ? a : b).join('\n')
    : null

  const needsSpiffs = configs.some(c => c.spiffs)
  const compileOpts = [...new Set(configs.flatMap(c => c.compileOptions || []))]

  const srcList = srcs.map(s => `"${s}"`).join('\n                    ')
  let mainCmake = `idf_component_register(SRCS ${srcList}\n                    INCLUDE_DIRS ".")`
  if (needsSpiffs) {
    mainCmake += `\n\nspiffs_create_partition_image(storage ../spiffs FLASH_IN_PROJECT)`
  }
  if (compileOpts.length > 0) {
    mainCmake += `\ntarget_compile_options(\${COMPONENT_LIB} PRIVATE ${compileOpts.join(' ')})`
  }

  const rootCmake =
`cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(${projectName})`

  const files = {
    'CMakeLists.txt': rootCmake,
    'main/CMakeLists.txt': mainCmake,
    'sdkconfig.defaults': sdkconfig,
    '__mainFile': mainFile,
    '__framework': 'esp-idf',
    '__idfTarget': board.idfTarget || 'esp32s3',
  }
  if (idfComponentYml) files['main/idf_component.yml'] = idfComponentYml
  if (partitionsCsv)   files['partitions.csv'] = partitionsCsv

  return files
}

// ── Arduino Framework ─────────────────────────────────────────

function buildArduinoProjectFiles(board, projectName, selectedSkillIds) {
  const skills = board.skills.filter(s => selectedSkillIds.includes(s.id))
  const configs = skills.map(s => s.projectConfig).filter(Boolean)

  // Main entry: sketch.ino (Arduino standard)
  const mainFile = 'sketch.ino'

  // Collect Arduino libraries and build flags
  const libraries = [...new Set(configs.flatMap(c => c.arduinoLibraries || []))]
  const buildFlags = [...new Set(configs.flatMap(c => c.buildFlags || []))]
  const srcs = [mainFile, ...new Set(configs.flatMap(c => c.srcs || []))]

  const files = {
    [mainFile]: '',
    '__mainFile': mainFile,
    '__framework': 'arduino',
    '__boardFqbn': board.arduinoBoardId || '',
    '__libraries': JSON.stringify(libraries),
  }

  // Add additional source files as empty stubs
  srcs.filter(s => s !== mainFile).forEach(s => {
    if (!files[s]) files[s] = ''
  })

  if (buildFlags.length > 0) {
    files['__buildFlags'] = JSON.stringify(buildFlags)
  }

  return files
}

// ── STM32Cube HAL Framework ───────────────────────────────────

function buildStm32CubeProjectFiles(board, projectName, selectedSkillIds) {
  const skills = board.skills.filter(s => selectedSkillIds.includes(s.id))
  const configs = skills.map(s => s.projectConfig).filter(Boolean)

  const mainFile = 'Src/main.c'
  const srcs = [mainFile, ...new Set(configs.flatMap(c => c.srcs || []))]

  // Collect HAL modules needed
  const halModules = [...new Set(configs.flatMap(c => c.stm32HalModules || []))]
  const defines = [...new Set(configs.flatMap(c => c.defines || []))]
  const buildFlags = [...new Set(configs.flatMap(c => c.buildFlags || []))]

  // Generate Makefile
  const srcList = srcs.map(s => `  ${s}`).join(' \\\n')
  const incDirs = ['Inc', ...new Set(configs.flatMap(c => c.incDirs || []))]
    .map(d => `  ${d}`).join(' \\\n')
  const halSrcs = halModules.map(m => `  Drivers/STM32F1xx_HAL_Driver/Src/${m}.c`).join(' \\\n')
  const asmSrcs = ['startup_stm32f103xb.s'].join(' \\\n')

  const makefile =
`######################################
# Generated by esp32-vibe-coder
# Target: ${board.name}
# MCU: ${board.mcuType}
######################################

# Project
TARGET = ${projectName}

# Paths
BUILD_DIR = build
HAL_DRIVER = Drivers/STM32F1xx_HAL_Driver
CMSIS_DRIVER = Drivers/CMSIS

# C sources
C_SOURCES = \\\n${srcList}

# ASM sources
ASM_SOURCES = \\\n${asmSrcs}

# HAL sources
HAL_SOURCES = \\\n${halSrcs}

# Includes
C_INCLUDES = \\\n${incDirs} \\\n  Drivers/CMSIS/Device/ST/STM32F1xx/Include \\\n  Drivers/CMSIS/Include

# MCU
MCU = -mcpu=cortex-m3 -mthumb
FPU =
FLOAT-ABI =

# Compile flags
C_DEFS = ${defines.map(d => `-D${d}`).join(' ')}
CFLAGS = \$(MCU) \$(C_DEFS) -Wall -fdata-sections -ffunction-sections ${buildFlags.join(' ')}
LDFLAGS = \$(MCU) -specs=nano.specs -T${board.linkerscript || 'STM32F103C8Tx_FLASH.ld'} -Wl,-Map=\$(BUILD_DIR)/\$(TARGET).map,--cref -Wl,--gc-sections

# ********** Standard build rules below **********
# ( truncated for brevity — full Makefile template )`

  // Linker script
  const linkerscript =
`/*
 * ${board.linkerscript || 'STM32F103C8Tx_FLASH.ld'}
 * Generated by esp32-vibe-coder
 */
MEMORY
{
  RAM    (xrw) : ORIGIN = 0x20000000, LENGTH = 20K
  FLASH  (rx)  : ORIGIN = 0x08000000, LENGTH = 64K
}`

  // System init stub
  const mainStub = `/**
  ******************************************************************************
  * File Name          : ${mainFile}
  * Description        : Main program body
  ******************************************************************************
  * This file was generated by esp32-vibe-coder with ${board.name} hardware context.
  */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "gpio.h"

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();

  /* USER CODE BEGIN 1 */
  /* USER CODE END 1 */

  while (1)
  {
    /* USER CODE BEGIN 3 */
    /* USER CODE END 3 */
  }
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /* HSI + PLL config for 72MHz (STM32F103C8) */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV1;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /* SYSCLK = 72MHz, HCLK = SYSCLK, APB1 = 36MHz, APB2 = 72MHz */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                              | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

void Error_Handler(void)
{
  __disable_irq();
  while (1);
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* USER CODE END 6 */
}
#endif`

  const files = {
    [mainFile]: mainStub,
    'Makefile': makefile,
    board.linkerscript || 'STM32F103C8Tx_FLASH.ld': linkerscript,
    'Inc/main.h': `#ifndef __MAIN_H\n#define __MAIN_H\n\n#include "stm32f1xx_hal.h"\n\nvoid Error_Handler(void);\n\n#endif /* __MAIN_H */\n`,
    'Inc/gpio.h': `#ifndef __GPIO_H\n#define __GPIO_H\n\n#include "stm32f1xx_hal.h"\n\nvoid MX_GPIO_Init(void);\n\n#endif\n`,
    'Src/gpio.c': `#include "gpio.h"\n\nvoid MX_GPIO_Init(void)\n{\n  GPIO_InitTypeDef GPIO_InitStruct = {0};\n\n  __HAL_RCC_GPIOA_CLK_ENABLE();\n  __HAL_RCC_GPIOC_CLK_ENABLE();\n\n  /* PC13 = onboard LED (Blue Pill) */\n  GPIO_InitStruct.Pin = GPIO_PIN_13;\n  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;\n  GPIO_InitStruct.Pull = GPIO_NOPULL;\n  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;\n  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);\n}\n`,
    'Inc/stm32f1xx_it.h': `#ifndef __STM32F1XX_IT_H\n#define __STM32F1XX_IT_H\n\n#include "stm32f1xx_hal.h"\n\nvoid NMI_Handler(void);\nvoid HardFault_Handler(void);\nvoid SysTick_Handler(void);\n\n#endif\n`,
    'Src/stm32f1xx_it.c': `#include "stm32f1xx_it.h"\n\nvoid NMI_Handler(void) {}\nvoid HardFault_Handler(void) { while(1); }\nvoid SysTick_Handler(void) { HAL_IncTick(); }\n`,
    'startup_stm32f103xb.s': `; Generated by esp32-vibe-coder\n; Minimal startup file for STM32F103xB\n  .syntax unified\n  .cpu cortex-m3\n  .fpu softvfp\n  .thumb\n\n  .word  _estack\n  .word  Reset_Handler\n  .word  NMI_Handler\n  .word  HardFault_Handler\n  .word  0,0,0,0,0,0,0\n  .word  SysTick_Handler\n\n  .section .text.Reset_Handler\n  .weak  Reset_Handler\n  .type  Reset_Handler, %function\nReset_Handler:\n  ldr   r0, =_estack\n  mov   sp, r0\n  bl    main\n  b     .\n\n  .pool\n  .size Reset_Handler, .-Reset_Handler\n`,
    '__mainFile': mainFile,
    '__framework': 'stm32cube',
    '__mcuType': board.mcuType || 'STM32F103C8',
    '__linkerscript': board.linkerscript || 'STM32F103C8Tx_FLASH.ld',
  }

  if (halModules.length > 0) {
    files['__halModules'] = JSON.stringify(halModules)
  }

  return files
}

// ── Self-Evolution ────────────────────────────────────────────

/** Patch a skill's systemPrompt at runtime (self-evolution)
 *  Returns patched skill or null if not found */
export function patchSkill(boardId, skillId, type, content) {
  const board = getBoard(boardId)
  if (!board) return null

  const skill = board.skills.find(s => s.id === skillId)
  if (!skill) return null

  const section = type === 'pitfall' ? '### Pitfalls' : '### Usage'
  const entry = `- ${content}`
  if (skill.systemPrompt && skill.systemPrompt.includes(section)) {
    skill.systemPrompt = skill.systemPrompt.replace(section, `${section}\n${entry}`)
  } else {
    skill.systemPrompt = (skill.systemPrompt || '') + `\n\n${section}\n${entry}`
  }
  return skill
}
